- name: Add terraform repository
  yum_repository:
    name: terraform
    description: Terraform YUM repo
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    gpgcheck: no
- name: Install terraform
  dnf:
    name: terraform
    state: latest