---
- hosts: all
  become: yes
  tasks:
    - name: Upgrade all packages
      dnf:
        name: "*"
        state: latest
    - name: Autoremove unneeded packages installed as dependencies
      dnf:
        autoremove: yes
